#!/usr/bin/env bash

battery_status="$(acpi -b | cut -d' ' -f 3,4 | tr ',' ' ' | head -1)"

view_battery() {
    percentage=$(echo $battery_status | cut -d ' ' -f 2)
    charging=$(echo $battery_status | cut -d ' ' -f 1)

    if [[ "$charging" == "Discharging" ]]
    then
        icons=(         )
    else
        icons=(         )
    fi

    if   [ ${percentage%?} -le 10 ]; then echo "${icons[0]} $percentage";
    elif [ ${percentage%?} -le 20 ]; then echo "${icons[1]} $percentage";
    elif [ ${percentage%?} -le 30 ]; then echo "${icons[2]} $percentage";
    elif [ ${percentage%?} -le 40 ]; then echo "${icons[3]} $percentage";
    elif [ ${percentage%?} -le 50 ]; then echo "${icons[4]} $percentage";
    elif [ ${percentage%?} -le 60 ]; then echo "${icons[5]} $percentage";
    elif [ ${percentage%?} -le 70 ]; then echo "${icons[6]} $percentage";
    elif [ ${percentage%?} -le 80 ]; then echo "${icons[7]} $percentage";
    elif [ ${percentage%?} -le 90 ]; then echo "${icons[8]} $percentage";
    else                                  echo "${icons[9]} $percentage";
    fi
}

view_battery
