#!/usr/bin/env bash

iface=$(ip route | cut -d' ' -f 5 | head -1)
public_ip=$(curl --silent "https://icanhazip.com")

if   [[ "$iface" == "wlp0s20f3" ]]; then icon="直";
elif [[ "$iface" == "enp0s31f6" ]]; then icon="";
else                                     icon="睊";
fi

if [[ "$public_ip" == "" ]]
then
    public_ip="disconnected"
fi

echo "$icon $public_ip"
