#!/usr/bin/env bash

volume="$(amixer get Master | tail -1 | cut -d ' ' -f 6 | tr -d '[]%')"
muted="$(amixer get Master | tail -1 | cut -d ' ' -f 8)";

if   [ $muted == "[off]" ]; then echo " muted";
elif [ $volume -le 33  ]; then echo "奄  $volume%";
elif [ $volume -le 66  ]; then echo "奔  $volume%";
else                           echo "墳  $volume%";
fi
