#! /bin/sh

setxkbmap -option 'caps:hyper'
xcape -e "Hyper_L=Escape"
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr

fcitx &
sxhkd &
$HOME/.config/bspwm/bar.sh &
$HOME/.fehbg

case "$(cat /proc/acpi/bbswitch | cut -d ' ' -f 2)" in
    ON)
        xrandr --output HDMI-0 --right-of eDP-1-1 --scale 2x2
        bspc monitor eDP-1-1 -d 1 2 3 4 5
        bspc monitor HDMI-0  -d 6 7 8 9 0
        ;;
    OFF)
        bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
        ;;
esac

bspc config border_width 0
bspc config window_gap  25

bspc config split_ratio               0.6
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_follows_pointer     true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
