#! /bin/sh

setxkbmap -option 'caps:hyper'
xcape -e "Hyper_L=Escape"
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr

case "$(cat /proc/acpi/bbswitch | cut -d ' ' -f 2)" in
    ON)
        xrandr --setprovideroutputsource modesetting NVIDIA-0
        xrandr --auto
        xrandr --output HDMI-0 --right-of eDP-1-1 --scale 2x2
        bspc monitor eDP-1-1 -d 1 2 3 4 5
        bspc monitor HDMI-0  -d 6 7 8 9 0
        ;;
    OFF)
        bspc monitor -d 1 2 3 4 5 6 7 8 9 0
        ;;
esac

sxhkd &
redshift &
feh --no-fehbg --bg-fill $HOME/Pictures/wallpaper.jpg

bspc config window_gap  25
bspc config border_width 4

bspc config normal_border_color  '#3b4252'
bspc config focused_border_color '#81a1c1'

bspc config split_ratio               0.55
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_follows_pointer     true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
