#! /bin/sh

case "$(cat /proc/acpi/bbswitch | cut -d ' ' -f 2)" in
    ON)
        xrandr --setprovideroutputsource modesetting NVIDIA-0
        xrandr --auto
        xrandr --output HDMI-0 --right-of eDP-1-1 --scale 2x2
        bspc monitor eDP-1-1 -d 1 2 3 4 5
        bspc monitor HDMI-0  -d 6 7 8 9 0
        ;;
    OFF)
        bspc monitor -d 1 2 3 4 5 6 7 8 9 0
        ;;
esac

gpg-connect-agent /bye
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

export XMODIFIERS="@im=fcitx"
export QT_IM_MODULE=fcitx
export GTK_IM_MODULE=fcitx

sxhkd &
fcitx &
redshift &
feh --no-fehbg --bg-fill $HOME/Pictures/wallpaper.jpg
polybar nord &
syncthing | logger &
urxvtd --quiet --opendisplay --fork

bspc config window_gap  25
bspc config border_width 5

bspc config normal_border_color  "#282C34"
bspc config focused_border_color "#61AFEF"

bspc config split_ratio               0.55
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_follows_pointer     true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config external_rules_command    $HOME/.config/bspwm/external_rules

bspc rule --add '*:zathura'  state=tiled
