#!/bin/sh

run_once () {
    killall --quiet $1
    $@ &
}

main() {
    run_once compton
    run_once redshift
    run_once dunst

    xrandr --auto
    xrandr --output HDMI-0 --scale 2x2 --right-of eDP-1-1
    xcape -e "Hyper_L=Escape"
    /home/mi/.fehbg
}

main
