#!/usr/bin/env bash

get_workspaces() {
    jq_cmd=
    i3-msg -t get_workspaces \
        | jq -r '.[] | if .focused then "<b>"+.name+"</b>" else .name end' \
        | xargs
}

dunstify --replace 1000 --timeout 3000 "Workspace" "$(get_workspaces)"
