#!/usr/bin/env bash

sudo efibootmgr \
    --disk /dev/nvme0n1 \
    --part 1 \
    --create \
    --label "Gentoo Linux" \
    --loader /vmlinuz-5.1.7-gentoo \
    --unicode "root=/dev/nvme0n1p2 rw rootfstype=ext4 intel_iommu=on pcie_acs_override=downstream,multifunction"
