#!/bin/bash

set -e

iptables  --flush
iptables  --delete-chain

iptables  --policy INPUT   DROP
iptables  --policy FORWARD DROP
iptables  --policy OUTPUT  ACCEPT

iptables  --append INPUT --in-interface lo                               --jump ACCEPT
iptables  --append INPUT --match conntrack --ctstate RELATED,ESTABLISHED --jump ACCEPT
iptables  --append INPUT --match conntrack --ctstate INVALID             --jump DROP

ip6tables --flush
ip6tables --delete-chain

ip6tables --policy INPUT   DROP
ip6tables --policy FORWARD DROP
ip6tables --policy OUTPUT  ACCEPT

ip6tables --append INPUT --in-interface lo                               --jump ACCEPT
ip6tables --append INPUT --match conntrack --ctstate RELATED,ESTABLISHED --jump ACCEPT
ip6tables --append INPUT --match conntrack --ctstate INVALID             --jump DROP

# syncthing
iptables  --append INPUT --protocol TCP --dport 22000 --jump ACCEPT
iptables  --append INPUT --protocol UDP --dport 21027 --jump ACCEPT
ip6tables --append INPUT --protocol TCP --dport 22000 --jump ACCEPT
ip6tables --append INPUT --protocol UDP --dport 21027 --jump ACCEPT
